### ISSUE TITLE
Log Pile error

### ISSUE THREAD

**Issue by swadams2** [InfoSecInnovations/What2Log#3]
I checked the minimal and ideal checkboxes for Ubuntu on the Log Pile form, clicked the "Get my Scripts" button, and got this error:
TypeError: Cannot read properties of undefined (reading 'view')
    at 13b559d.js:1:6738
    at Array.map (<anonymous>)
    at f.getScripts (13b559d.js:1:6690)
    at ee (9c49149.js:2:11519)
    at HTMLDivElement.n (9c49149.js:2:13267)
    at HTMLDivElement.Dr.c._wrapper (9c49149.js:2:45571)

**Comment by soundsofthetime** [comment]
We made a couple of changes and updated the site, please see if the issue persists, but it should be fixed now

**Comment by soundsofthetime** [comment]
We made a couple of changes and updated the site, please see if the issue persists, but it should be fixed now

**Comment by swadams2** [comment]
It worked.  Thanks for fixing it.
